source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'
pod 'GoogleMaps'
pod 'ASIHTTPRequest'
pod 'LGFilterView'
pod 'JTProgressHUD’
pod 'NYAlertViewController'
pod 'MHVideoPhotoGallery'
pod 'NJKScrollFullScreen'
pod 'FXBlurView'
pod 'TNSexyImageUploadProgress'
pod 'MXSegmentedPager'
pod 'STCollapseTableView'
pod 'UIImage-Helpers'